{ modulename: 'C:\\Users\\lakshaya.sood\\Downloads\\QMS\\qms_ui\\build\\server',
  'trace-id': '39764f20-0f3c-11e9-ada0-cdc9d864aee2',
  url: null,
  browser: null,
  os: null,
  device: null,
  ip: null,
  'session-id': null,
  calltreeid: null,
  'remote-user': null,
  user: null,
  level: '\u001b[32minfo\u001b[39m',
  message: 'Server started listening on port 7000.',
  label: 'logger.js',
  timestamp: '2019-01-03 15:14:54',
  [Symbol(level)]: 'info',
  [Symbol(splat)]:
   [ { modulename: 'C:\\Users\\lakshaya.sood\\Downloads\\QMS\\qms_ui\\build\\server',
       'trace-id': '39764f20-0f3c-11e9-ada0-cdc9d864aee2',
       url: null,
       browser: null,
       os: null,
       device: null,
       ip: null,
       'session-id': null,
       calltreeid: null,
       'remote-user': null,
       user: null } ],
  [Symbol(message)]: '\u001b[32minfo\u001b[39m: Server started listening on port 7000. {"modulename":"C:\\\\Users\\\\lakshaya.sood\\\\Downloads\\\\QMS\\\\qms_ui\\\\build\\\\server","trace-id":"39764f20-0f3c-11e9-ada0-cdc9d864aee2","url":null,"browser":null,"os":null,"device":null,"ip":null,"session-id":null,"calltreeid":null,"remote-user":null,"user":null,"label":"logger.js"}' }